gdrive_folder_id = "請貼上你的Drive資料夾ID"

[gdrive_credentials]
type = "service_account"
project_id = "agile-extension-491506-b1"
private_key_id = "118a17b399aabe7096eb72069b703570759ce670"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDlOT0+wWlAyBIN
GYVLgp5X0cMqMXD989cj6YXzbEorrDuVB9avC3/etOBMPA/92bOlxL9N7vofent6
Rcx7WsbTRhaXzsUAGs2Ib8QgibsNA94VPW5dmjUC7u3yVQcQBOQsiwqAY9+V7ay9
hXYDqoh5I6feG+Zn4xRBFoXx9g93vQydT2pPMLLqI+q93n1P2pnUcDyf2EcDsi0e
ItpwYzul+dnXp99JrLbHA89QJhSS7jTCDmSF4vY2YdpZRHX3/riMvTqXgzyHz/wV
Q+WwvhHAs21l8BLbybBAv1pJdaQ6CKLQg9Pbyxx+CaAdXpAsUfv9Aj2g7bUxMwXe
DXyeIdcFAgMBAAECggEADSOJR6oVauGs6zRNyCS+B8GdwrLfy6ao68WMaIYKAFPY
fHPdEd6CX1UV0DjXH9FVM0jCQGjUzG4cWsdab62l3OFVFTGEaDuhEVN6tfS/FIFm
vuftBg97P2ZLnErUY04seAMmQHK5E6JydtCKEa66MNti2V/XBphlBlAQsGxOuamw
HsGYLTcx2vtVK/OyORGuxkkQXoKd1QIB2co0PCdEcvvQtmryKZ5ORRhfCfStWEs6
ykv4UxXLNDjF6oIVrYzEBBITs4Tq8zpDZFLoErhx0TyYjcUriXm8NeTPW59n4oiu
KkHn3dAQ79qDT29+SgX1fJf15/VN2dl1GwVTkkmj8QKBgQD8VQ0AI+YV5PTOFhot
BWmv/4ee6vdJZPb+zl+y2khMZsxrdmbylbP9MPuQ3aUE21YtLQjOn7qWQMRzsHUr
DvGHOq/VX/DnNnzOWZ/3etbjP9YGSCtFXkS4oSF3Bp1hBnFX7ug4YpojLTEJprtB
zXBgBzX1Z23eB6R0GBDoS3YAiQKBgQDojjMEids4QCdd2qYT7VtJcj2WNIWl+PiG
M/Q4St561PvoawWp+zBgN0vN1/ZtQMWUyLqUbhsiYtvIF7iwTmRrFmqAeE37fOzp
4pnZ/vCm12KlwQDaza14Cmd0N7f1pxBychysFjXLoK97poaQ81wsdy579HNZJSyk
njFJNyirnQKBgQC+ChgmeOL6rlspM0A3lBIK+TpdF71yS1YyhZ9RhlBZKjre3Geg
X9sU32U3r5Zu1/pJP9eYNnhCXTkXoFg+O5zwKeTvoLhAiqrohluR+bQJprQ8OvJL
5jl/i+s2R4cT4dRPU6EVhj1sLMb369iwMFdoG0YqMuFuDPdwcAeby+ltcQKBgF9k
rTLIZb8+Oae7H/L+ozqOfQrXQpdheHh8aUqKE5bpNOgStoESg7aEGDk4xGHudt3g
NQDb5Y+GY8dBS8YuceynhkpqjvqBNSF/jUKp3AdkRJffgr0+L1EVW3iFvpUq0YlQ
m8hPWAPORw1+sqZU3VN0FAJOtN41bImeRnNVB/7VAoGBALMbTVtru8BDaosd3Vpq
47rofQdMIi9E/po7BnBdGNlBLB1W8K/aHxXAZmfRHY7fYpG5VTnAdUHw7YA41B+m
3LC9KTCW29em+wJ7jfX4nyGxVDnL+EKI8HqTvXV9z42rnazt9bPC2U7SQqfvaXb4
BbSL3xog5mI5LSwYYEyGSj8O
-----END PRIVATE KEY-----
"""
client_email = "streamlit-drive-sync@agile-extension-491506-b1.iam.gserviceaccount.com"
client_id = "118229834800767236819"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive-sync%40agile-extension-491506-b1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

pdf_password = "請填入身分證字號"

email_sender = "請填入Gmail"
email_app_password = "請填入16碼應用程式密碼"
email_recipient_alan = "請填入Alan的Email"
email_recipient_lydia = "請填入Lydia的Email"